### ISSUE TITLE
Extract the image pre-processing

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#12]
Currently there is common process is applied to the reference image as to each "test" image. It would be great to extract this into a method/function/class as per DRY.

**Comment by jmccormac01** [comment]
Do you mean the correction steps? ```normalise``` and ```subtract_bkg```?

**Comment by jmccormac01** [comment]
Fixed in f981dc1 (b4bb3d4 had indentation errors after editor issue). Closing.
