### ISSUE TITLE
Split test data out from the package

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#16]
Currently the package distributions weigh in at around 15MB each, which is quite a lot for a simple python script.

Astropy packages have a convention for hosting external datasets which may be useful for us as it will allow us to create a much smaller package which is less of a download for our users.

The other alternative is to not package the tests along with the package, which is ok for end users and developers/contributors will be cloning the git repo anyway.

**Comment by jmccormac01** [comment]
I was looking at this last night. There are some guidelines [here](http://docs.astropy.org/en/stable/development/codeguide.html) on how to store/access the data. I was too tired to start on it :) Maybe this evening I'll get round to it.

**Comment by mindriot101** [comment]
The astropy module includes a function `get_readable_fileobj` which can treat a remote file (accesible by a url) as a local file object.  This also caches the download so remote access is only needed once.

I see a helper function in the tests which is something like:


```python
import tempfile
from contextlib import contextmanager
from astropy.utils.data import get_readable_fileobj

@contextmanager
def download_remote_file(url):
    '''Given a remote file location, download the file with optional
    caching and return the file name.
    '''
    with tempfile.NamedTemporaryFile(suffix='.fits') as tfile:
        with get_readable_fileobj(url, cache=True) as fobj:
            tfile.write(fobj.read())

        tfile.seek(0)
        yield tfile.name
```

and the usage could be something like:

```python
from astropy.io import fits

with download_remote_file(url) as filename:
    with fits.open(filename) as hdulist:
        pass
```

One trouble I see with this approach is when testing the above code on Python 3.5 there are some errors to do with the shelve library, so we may have to do something different on Python 3.5.

We also need to find somewhere to host the files. We do have an astro web server we could use (http://deneb.astro.warwick.ac.uk/phsnag/ for example) but this is tied to my CSC account (which runs out next April), and as a minor point the data are not served over https.

Astropy does have a central storage location under data.astro.py.org but I'm not sure affiliated packages can use that space.

**Comment by mindriot101** [comment]
Amazon S3 looks pretty cheap ($0.01 per month) for low volume downloads, and they're served over https

**Comment by mindriot101** [comment]
Using James' web server http://www.jamesjmccormac.com/donuts/data

Still need to remove the data from the git repository, but at least it's out of the pypi packages.

**Comment by mindriot101** [comment]
With the package refresh this is now done
