### ISSUE TITLE
Set up system for pypi uploads

### ISSUE THREAD

**Issue by jmccormac01** [jmccormac01/Donuts#17]
I thought we had to manually put versions on Pypi, they are uploading automatically. Also dev160 is failing to import and complaining about builtins

```python
>>> import donuts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/donuts/__init__.py", line 10, in <module>
    from ._astropy_init import *
  File "/usr/local/lib/python2.7/site-packages/donuts/_astropy_init.py", line 13, in <module>
    import builtins as builtins
ImportError: No module named builtins
>>> from donuts import Donuts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/donuts/__init__.py", line 10, in <module>
    from ._astropy_init import *
  File "/usr/local/lib/python2.7/site-packages/donuts/_astropy_init.py", line 13, in <module>
    import builtins as builtins
ImportError: No module named builtins
>>> 
```

**Comment by mindriot101** [comment]
I uploaded a new version to pypi which is why this version is there, sorry!

    Simon

**Comment by jmccormac01** [comment]
Ah, maybe I misunderstood. I thought pypi would be a copy of the most stable master? I don't mind either way

**Comment by jmccormac01** [comment]
it was showing commit 160 and hiding the one I did manually. 160 was my last push so it seems it is tracking what we do live, unless you just did it a few minutes ago?

**Comment by mindriot101** [comment]
Hmm no this was last night. Strange, I don't completely understand the astropy version number incrementer system. I assumed it just added one for every commit on a branch.

    Simon

**Comment by jmccormac01** [comment]
I am a bit confused. Did you upload 0.0dev160 manually? That makes sense as we are currently on 0.0dev164 with the 4 commits I just made. Should we make pypi track the last stable commit of the master branch only? Also, how often to merge devel as we are 16 commits ahead now.

**Comment by mindriot101** [comment]
> Did you upload 0.0dev160 manually?

Yup

> Should we make pypi track the last stable commit of the master branch only?

We could make our commits automatically push to pypi but I think that

> how often to merge devel as we are 16 commits ahead now.

we should continue to upload manually, and merge devel into master when we feel we need to bump the version number.

Common convention these days is semantic versioning: http://semver.org/:

* bump the major version number when there are backward incompatible changes
* bump the minor version when backward compatible changes are released
* bump the patch version when small changes are made

Note: version 1.0.0 has a very specific meaning => that it's production ready and relatively stable, as every commit with backwards-incompatible changes require a MAJOR version bump. Before that, basically anything goes!

For the time being I vote we start bumping the minor version number with every few commits that we feel are related, are a significant chunk of work or are approximately related.

What do you think?

    Simon

**Comment by mindriot101** [comment]
I believe the error message was caused by my misunderstanding of universal wheels - the astropy code performs a python version check, which may not generate a wheel in a valid way. 5a1bcea8cdb5e351138091bc4edb192fcec37f12 shows my fix

**Comment by jmccormac01** [comment]
This has been included in the makefile. Closing.
