### ISSUE TITLE
Get the package registered on pypi before somebody else does!

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#2]
Currently there is no package at https://pypi.python.org/pypi/donuts which - given how common the name is - is relatively surprising! It might be worth registering it fairly soon.

**Comment by jmccormac01** [comment]
I think I've done this now. Send me your PyPi user name and I'll add you as an owner

**Comment by jmccormac01** [comment]
Ok, this is done. I've just confirmed. Closing.
