### ISSUE TITLE
Updating astropy helpers

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#21]
We are using a submodule `astropy_helpers` which came as part of the `astropy` package template. Do we have a policy on updating this repository? We could:
- stick with the same version we have now, and risk bugs and best-practice changes, or
- update every now and again, and perform extensive testing

Already there have been [many changes](https://github.com/astropy/astropy-helpers/compare/244c9dd63d291f02c9cadc483d3a9e7a07c124c3...111b1e5d1d05e2dd9a73d13862327ac6f854be8a) which will need reviewing.

**Comment by jmccormac01** [comment]
Removing connection to astropy soon. Closing.
