### ISSUE TITLE
Releasing data

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#3]
Do we want to package NGTS data along with the code, even in the tests? We may run into licensing/proprietary period related questions...

I have the idea of synthesising test data for ourselves (e.g. making two identical images -> the deltas should be 0, making offset images and asserting the deltas)

**Comment by mindriot101** [comment]
See #4

**Comment by jmccormac01** [comment]
I have INT data that is public now. I am sure we could use that?

**Comment by jmccormac01** [comment]
The tests cannot find the data files. I've trie moving them around to different relative paths but I'm missing how to make it point to the data. I obviously don't want to hard code a path to it, but a relative path in the source tree should be ok, right?

**Comment by mindriot101** [comment]
The reason for the tests not finding the images is that the tests are run from the `build` subdir, so probably the images (if we include them) will have to be supplied as part of something like `package_data` in `setup.py`. I don't quite know off the top of my head so some experimentation is needed unfortunately :(

**Comment by mindriot101** [comment]
Ok to include test data:

* Add a subdirectory of the package called `data` and add all data files there -> this is picked up by this part of `setup.py`:
```python
# Add the project-global data
package_info['package_data'].setdefault(PACKAGENAME, [])
package_info['package_data'][PACKAGENAME].append('data/*')
```
* find this subpath from the tests, e.g.:
```python
ROOT_PATH = os.path.dirname(__file__)
DATA_DIR = os.path.join(ROOT_PATH, '..', 'data')
# then use the relative paths in tests
test_filename = os.path.join(DATA_DIR, 'test.fits')
```

**Comment by jmccormac01** [comment]
I've updated test_integration, see (376d02e)

**Comment by jmccormac01** [comment]
Ok. Got this to work by putting the data directory in the same parent folder as tests, not up one level as I had previously done. The egg_info test is still failing. It cannot find numpy. I'm not quite sure what the issue is. I'll keep digging.

**Comment by mindriot101** [comment]
Sorted out the `egg_info` tests => it was importing the package to get the metadata, which is bad practice. [This change](https://github.com/jmccormac01/Donuts/commit/d27d85deee7dae8d067bbd42cb7ede199a917c0e) sorts out the problem (shamelessly copied from the `photutils` `setup.py`). Closing.
