### ISSUE TITLE
Support calculations over arbitrary sub-image areas / frame sizes

### ISSUE THREAD

**Issue by pchote** [jmccormac01/Donuts#35]
Frames acquired by the Warwick 1m telescope can have arbitrary sizes and plate scales depending on the CCD windowing and binning.

The current hardcoded background tile size and trimming could be replaced by commandline arguments for the `[x1:x2,y1:y2]` guide window and (minimum) background tile size.

See [warwick-one-metre/pixelshift/framedata.c#L119](https://github.com/warwick-one-metre/pixelshift/blob/b11b74da05f59cfc5ddd9f1c4cfcfb285486f823/framedata.c#L119) for a reference implementation.

**Comment by jmccormac01** [comment]
We are looking at a new release soon. Do you think adding this option is fine and default to the standard behaviour?

**Comment by mindriot101** [comment]
Discussion moved to PR #44

**Comment by jmccormac01** [comment]
This was done in [this commit](https://github.com/jmccormac01/Donuts/commit/08a0a964184d73e6ae0fac0b04ace22d7ec9baa0)

- The image geometry is now worked out only once (was being done for every image before...)
- The automated slicing of the image is now more robust to strangely shaped sensors, a warning is given when up to 'ntiles' pixels are clipped of the top and right of the image to allow for integer division of the axes sizes and ntiles. 
- A new ```calculation_area_override``` is available to specify a specific region of the detector to use. I was lazy and provide no checking off the plethora of wrong ways to enter this data (+ve numbers, on image numbers, limits the right way round etc etc). I can add checks if it becomes an issue. 'ntiles' must be supplied to match the dimensions of the image.
