### ISSUE TITLE
Update the docs to describe new object returned from measure_shift()

### ISSUE THREAD

**Issue by jmccormac01** [jmccormac01/Donuts#36]
The docs are a little out of date, update for the new changes in v0.1.0

**Comment by mindriot101** [comment]
I may have created an infinite loop somewhere - the docs are no longer building :(

**Comment by mindriot101** [comment]
Possibly a known issue: https://github.com/rtfd/readthedocs.org/issues/2255

**Comment by advancedrei** [comment]
So I think the build service is totally hosed for everyone at the moment... is anyone looking into it?

**Comment by mindriot101** [comment]
It seems to be resolved now, the issue was on readthedocs's end
