### ISSUE TITLE
Check that the tests are running with valid versions of astropy

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#40]
> Hi,
> 
> The problems with conda last week highlighted that continuum does not provide builds for a number of astropy/python/numpy combinations for which are commonly used for testing in affiliated packages (and in the matrix in the package template).
> 
> As of earlier today, these astropy builds are now available on the conda channel astropy-ci-extras (most affiliated packages are probably already using the channel since it is in the template and ci-helpers):
> 
> python 2.7:
> - Builds of the latest astropy LTS (1.0.10) for numpy 1.7 through 1.11
> - Builds of the latest astropy release (1.2) for numpy 1.7 through 1.10 (continuum provides the numpy 1.11 build)
> 
> python 3.5:
> - Builds of astropy LTS (1.0.10) for the versions of numpy provided by continuum (1.9, 1.10, 1.11)
> - Builds of astropy stable (1.2) for numpy 1.9 and 1.10 (continuum provides the numpy 1.11 build).
> 
> To get a better handle on what other builds would be useful for package developers, please take a few minutes to fill out this survey if you work on an affiliated package or use the astropy-ci-extras channel as part of your continuous integration: http://goo.gl/forms/qJvQiVt0ynTfOCq22
> 
> Thanks,
> Matt Craig 
> 
> PS It is a good sign of the state of the astropy community that in the ~20 hours since some of these builds became available they've been downloaded for CI tests 171 times!

**Comment by jmccormac01** [comment]
Removing connections to astropy in the new year, closing.
