### ISSUE TITLE
Fix shape assignment order in remove_background

### ISSUE THREAD

**Issue by ppmim** [jmccormac01/Donuts#41]
When running donuts with 1024x1024 images and overscan_width=20, prescan_width=20, a shape mismatch happens during subtraction:

   self.backsub_region = self.raw_region - self.sky_background.

Swapping assignment order to:

dim_y, dim_x = self.raw_region.shape 

fixes the problem.

**Comment by mindriot101** [comment]
Thanks for pointing this out, we'll take a look cc @jmccormac01

**Comment by jmccormac01** [comment]
Well spotted. In my local development copy (which is many iterations older than this repo) the order is ```dim_y, dim_x``` as you suggested. This must have gotten mixed up during the recent upgrades. We'll fix this and release 0.2.1 soon. This should solve your documentation issue also. Thanks!
