### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by filipematos95** [jmccormac01/Donuts#54]
I am trying to use donuts, but when I create my Donuts object I get a ZeroDivisionError. I am using the sample code: 

`d = Donuts(refimage=DIR+reference_image_name,image_ext=0,
	overscan_width=20,prescan_width=20,border=64,
	normalise=True,exposure='EXPOSURE',subtract_bkg=True,
	ntiles=32)
`
 with the attached fits file (just remove the .txt only used for uploading here) 
[elp1m008-fl05-20160424-0173-e90_cropped.fits.txt](https://github.com/jmccormac01/Donuts/files/1579405/elp1m008-fl05-20160424-0173-e90_cropped.fits.txt)

**Comment by jmccormac01** [comment]
Hi @filipematos95 I just seen this, sorry for the delay. I'll take a look and get back to you.

**Comment by jmccormac01** [comment]
@filipematos95 ok so a quick look at your image shows it is only 155 x 155 pixels  (Y x X). You have set Donuts up (using your example above) with a prescan and overscan width of 20 each. This ignores 20 pixels along the left and right side of the image leaving 155 x 115 pixels to work on. Then the border is set to 64 which removes a boarder of 64 pixels from all around the edge of the image area, effectively removing all of the image. 

With such a small image I would set up Donuts without any background subtraction or trimming. The following worked fine for me:

```python
from donuts import Donuts
ref = Donuts(refimage='elp1m008-fl05-20160424-0173-e90_cropped.fits',
                      border=0,
                      normalise=True, 
                      subtract_bkg=False) 
```

I would keep the normalisation if you are going to change exptimes during a run. If not you can set that to false too. If you look in the docs at the link below you can see the defaults for each setting, some of the assumptions are fine but some are not good for this type of postage stamp image. 

https://donuts.readthedocs.io/en/latest/donuts/api.html

Please let me know how this works. I've not tested things a lot on this type of data. I am keen to know how it works. Thanks!

**Comment by jmccormac01** [comment]
I'm closing this as no response in 5 months.
