### ISSUE TITLE
Add landscape.io health checking

### ISSUE THREAD

**Issue by mindriot101** [jmccormac01/Donuts#7]
This is a CI site which checks for code quality (using e.g. pylint etc.). We could add integration pretty easily and fix the problems...

**Comment by jmccormac01** [comment]
I've done this now and it seems like most of the problems it flags are part of the astropy template package and not our code. See [https://landscape.io/github/jmccormac01/Donuts](here). It is reporting 86% as excellent.

**Comment by mindriot101** [comment]
I've raised the score by excluding the astropy files from landscape. Closing
